version: '2'
networks:
  ustream:
    name: ustream-network
    ipam:
      driver: default
services:
  zookeeper:
    image: debezium/zookeeper:0.9
    networks:
      - ustream
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:0.9
    networks:
      - ustream
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: mysql:latest
    networks:
      - ustream
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
      - "./init:/docker-entrypoint-initdb.d/:ro"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ustream
      MYSQL_USER: staging
      MYSQL_PASSWORD: stagingpw
  connect:
    image: debezium/connect:0.9
    networks:
      - ustream
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
     - zookeeper
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses

