version: '2'
networks:
  debezium:
    name: debezium-network
    ipam:
      driver: default
services:
  zookeeper:
    image: debezium/zookeeper:latest
    container_name: dz_zookeeper
    networks:
      - debezium
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:latest
    container_name: dz_kafka
    networks:
      - debezium
    ports:
      - 19092:19092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://kafka:19092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CONNECTIONS_FROM_HOST://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONNECTIONS_FROM_HOST:PLAINTEXT
  mysql:
    image: mysql:latest
    container_name: dz_mysql
    networks:
      - debezium
    volumes:
      - "./mysql/.mysql-data/db:/var/lib/mysql"
      - "./mysql/custom-mysql.cnf:/etc/mysql/conf.d/mysql.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/:ro"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer
      MYSQL_USER: debeziumuser
      MYSQL_PASSWORD: debeziumpw
  connect:
    image: debezium/connect:latest
    container_name: connect
    networks:
      - debezium
    ports:
     - 8083:8083
    links:
     - kafka
     - mysql
     - zookeeper
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
  ksqldb-server:
    container_name: dz_ksql_server
    networks:
      - debezium
    image: confluentinc/cp-ksql-server:latest
    hostname: ksqldb-server
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    environment:
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_BOOTSTRAP_SERVERS: kafka:9092
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  ksqldb-cli:
    container_name: dz_ksql_cli
    networks:
      - debezium
    image: confluentinc/cp-ksql-cli:latest
    depends_on:
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true
  avro-schema-registry:
    networks:
      - debezium
    container_name: dz_avro_registry
    image: confluentinc/cp-schema-registry:latest
    restart: always
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"
      SCHEMA_REGISTRY_HOST_NAME: avro-schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8881"
    ports:
      - 8881:8881
